ArraySum
deepakmanikantak/training-automation pull request #1
Opened 2020-04-25 16:07 UTC by Aizaz-tachyon

2020-04-25 16:43 UTC, deepakmanikantak requested changes

2020-04-25 16:43 UTC, deepakmanikantak commented on src/com/trainee/aizaz/java/ArraySum.java
> +}
Reformat the Whole Code
Intelli > Toolbar > Code > Reformat Code & Optimize imports & Auto indent Line

2020-04-25 16:44 UTC, deepakmanikantak commented on src/com/trainee/aizaz/java/ArraySum.java
> +}
There is no Exception handling..
The code is failing when i input the String instead of int value

2020-04-25 17:26 UTC, Aizaz-tachyon reviewed
i have made the changes and i have reformat the code as well as added exceptions

2020-04-26 08:15 UTC, deepakmanikantak approved these changes

2020-04-26 08:15 UTC, merged